name: Maintenance

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  maintenance:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          # If the repo is packaged, install it in editable mode (optional, but harmless)
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m pip install -e .
          fi

      - name: Run Maintenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # These can be overridden if you use different paths
          BILLING_TAG: billing-state-v1
          BILLING_TEMPLATE_DIR: releases/billing-state-v1
          BILLING_STATE_DIR: .billing-state
        run: |
          set -euo pipefail
          bash scripts/run_maintenance.sh

      - name: Verify repository invariants (modules/tenants/maintenance-state)
        run: |
          set -euo pipefail
          python scripts/ci_verify.py --phase pre

      - name: Auto-commit maintenance-state updates (push-triggered)
        if: ${{ github.event_name == 'push' }}
        run: |
          set -euo pipefail
          if git diff --quiet -- maintenance-state; then
            echo "[MAINTENANCE] maintenance-state/: no changes to commit."
            exit 0
          fi

          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add maintenance-state
          if git diff --cached --quiet; then
            echo "[MAINTENANCE] Nothing staged after git add maintenance-state."
            exit 0
          fi

          git commit -m "chore(maintenance): refresh maintenance-state"
          git push origin "HEAD:${GITHUB_REF_NAME}"

      - name: Ensure maintenance-state is committed
        run: |
          set -euo pipefail
          if ! git diff --quiet -- maintenance-state; then
            echo "[MAINTENANCE][FAIL] maintenance-state/ is out-of-date even after maintenance run." >&2
            git --no-pager diff -- maintenance-state | sed -n '1,200p' >&2 || true
            exit 2
          fi

      - name: Verify local billing-state bootstrap (headers + ID format)
        run: |
          set -euo pipefail
          python scripts/ci_verify.py --phase post --billing-state-dir .billing-state

  cache_prune:
    name: Cache Prune (called)
    needs: maintenance
    uses: ./.github/workflows/cache-prune.yml
    with:
      dry_run: true
    secrets: inherit
    permissions:
      actions: write
      contents: write

  e2e_verify:
    name: E2E Verify (called)
    needs: maintenance
    uses: ./.github/workflows/e2e-verify.yml
    permissions:
      contents: read
