from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict


def run(params: Dict[str, Any], outputs_dir: Path) -> Dict[str, Any]:
    """Module entrypoint.

    This function is imported and called by the platform module executor.
    It must be deterministic: given the same inputs, it should produce the same outputs.

    Returns:
        Dict with keys:
          - files: list of produced file paths (relative to outputs_dir)

    """
    topic = str(params.get("topic", "")).strip()
    language = str(params.get("language", "")).strip()
    freshness_days = str(params.get("freshness_days", "")).strip()

    # The executor performs required-field validation; this is a last-resort guard.
    text = (
        f"TOPIC: {topic}\n"
        f"LANGUAGE: {language}\n"
        f"FRESHNESS_DAYS: {freshness_days}\n"
        "\n"
        "This is a placeholder output generated by module U2T.\n"
    )

    out_file = outputs_dir / "source_text.txt"
    out_file.write_text(text, encoding="utf-8")

    report = {
        "topic": topic,
        "language": language,
        "freshness_days": freshness_days,
        "files": ["source_text.txt"],
    }
    (outputs_dir / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    return {"status": "COMPLETED", "files": ["source_text.txt", "report.json"]}
